{% set name = "jiter" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jiter-{{ version }}.tar.gz
  sha256: cd73d3e740666d0e639f678adb176fad25c1bcbdae88d8d7b857e1783bb4212d

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - maturin
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1,<2
    - pip
  run:
    - python

test:
  imports:
    - jiter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://crates.io/crates/jiter
  summary: Fast iterable JSON parser.
  license: MIT
  license_file: crates/jiter/LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
