{% set name = "jiter" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jiter-{{ version }}.tar.gz
  sha256: e19cd21221fc139fb032e4112986656cb2739e9fe6d84c13956ab30ccc7d4449

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - maturin
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1,<2
    - pip
  run:
    - python

test:
  imports:
    - jiter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://crates.io/crates/jiter
  summary: Fast iterable JSON parser.
  license: MIT
  license_file: crates/jiter/LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
